//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaoXin.Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_People
    {
        public int PeopleId { get; set; }
        public string PeopleNum { get; set; }
        public string PeopleName { get; set; }
        public string PeopleAdd { get; set; }
        public string PeopleEmail { get; set; }
        public string PeoplePhone { get; set; }
        public string PeoplePay { get; set; }
        public string Note { get; set; }
        public Nullable<bool> BoolLX { get; set; }
    }
}
