//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaoXin.Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Photo
    {
        public int PhotoId { get; set; }
        public string PhontName { get; set; }
        public string PhotoURL { get; set; }
        public string Note { get; set; }
        public Nullable<bool> BoolYX { get; set; }
    }
}
