//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaoXin.Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Order
    {
        public int ShopOrderID { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> PeopleId_buy { get; set; }
        public Nullable<int> GoodsId { get; set; }
        public Nullable<int> buyNum { get; set; }
        public Nullable<System.DateTime> butTime { get; set; }
        public Nullable<bool> BoolYX { get; set; }
        public Nullable<bool> BoolSeng { get; set; }
    }
}
