//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaoXin.Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public System.Guid Id { get; set; }
        public string Email { get; set; }
        public string NickName { get; set; }
        public string Password { get; set; }
        public string Contactqq { get; set; }
        public string Contactaddr { get; set; }
        public string UserName { get; set; }
        public string Mobile { get; set; }
        public string avatar { get; set; }
        public Nullable<int> RankCredits { get; set; }
        public Nullable<byte> IsOnline { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public string HeadImage { get; set; }
        public string HeadSmallImage { get; set; }
        public Nullable<bool> IsCanDel { get; set; }
        public Nullable<System.DateTime> DelTime { get; set; }
        public Nullable<bool> IsOtherDel { get; set; }
        public Nullable<System.DateTime> OtherDelTime { get; set; }
        public Nullable<bool> isadmin { get; set; }
    }
}
