//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaoXin.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendFile
    {
        public int id { get; set; }
        public string Accept_UserName { get; set; }
        public string Send_UserName { get; set; }
        public string Send_File { get; set; }
        public Nullable<System.DateTime> Send_Time { get; set; }
        public string Send_FileName { get; set; }
    }
}
