//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaoXin.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpeechInfo
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> FromUser { get; set; }
        public string SpeachContent { get; set; }
        public string SpeechImage { get; set; }
        public Nullable<byte> IsVip { get; set; }
        public Nullable<byte> State { get; set; }
        public Nullable<System.DateTime> SumbitTime { get; set; }
        public string DelUserId { get; set; }
        public Nullable<System.DateTime> DelTime { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string cityname { get; set; }
        public string Sourcecity { get; set; }
    }
}
